services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authservice-mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Auth@StrongPass123"   # min 8 ký tự, có chữ hoa + số + ký tự đặc biệt
      MSSQL_PID: "Developer"                    # bản miễn phí, không dùng production
    volumes:
      - mssql_data:/var/opt/mssql              # data persist khi restart container
  
  redis:
    image: redis:8
    container_name: redis
    command: redis-server --requirepass Anhquang4mat@2002
    ports:
      - "6379:6379"
volumes:
  mssql_data:
